import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getFirestore, collection, addDoc, onSnapshot, query, where, orderBy, limit, getDocs, deleteDoc, doc, updateDoc } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, updateProfile, signOut, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { firebaseConfig } from './firebase-config.js';

const APP_VERSION = '2.5.0';
const $ = selector => document.querySelector(selector);
const saved = (() => { try { return JSON.parse(localStorage.getItem('poupoules-state') || '{}'); } catch { return {}; } })();
const wasWiped = localStorage.getItem('poupoules-wiped') === '1';
const defaultHens = [
  { id: 'marguerite', name: 'Marguerite', breed: 'Sussex', emoji: '🐔', active: true },
  { id: 'caramelle', name: 'Caramelle', breed: 'Rousse', emoji: '🐓', active: true },
  { id: 'pistache', name: 'Pistache', breed: 'Araucana', emoji: '🐣', active: true },
  { id: 'colette', name: 'Colette', breed: 'Harco', emoji: '🐔', active: true },
  { id: 'suzette', name: 'Suzette', breed: 'Marans', emoji: '🐓', active: true },
  { id: 'praline', name: 'Praline', breed: 'Coucou', emoji: '🐣', active: true }
];
const demoEggs = [5, 7, 6, 8, 9, 7, 8];
let eggsByDay = wasWiped ? [] : (saved.eggsByDay?.length ? saved.eggsByDay : [...demoEggs]);
let eggEntries = wasWiped ? [] : (saved.eggEntries || []);
let hens = wasWiped ? [] : (saved.hens?.length ? saved.hens : structuredClone(defaultHens));
let activities = wasWiped ? [] : (saved.activities?.length ? saved.activities : [
  { icon: '🥚', title: 'Récolte enregistrée', text: '8 œufs ajoutés au journal', time: 'Il y a 2 h' },
  { icon: '💧', title: 'Abreuvoir rempli', text: 'Routine du matin terminée', time: 'Aujourd’hui' },
  { icon: '🐔', title: 'Pistache a pondu', text: 'Œuf bleu-vert identifié', time: 'Hier, 18:42' }
]);
let economics = { boxPrice: 0, ...(wasWiped ? {} : (saved.economics || {})) };
let transactions = wasWiped ? [] : (saved.transactions || []);
let profileName = wasWiped ? '' : (saved.profileName || '');
let firestore = null, auth = null, currentUser = null, unsubscribeEggs = null, editingHenId = null, pendingPhoto = '';

const persist = () => { try { localStorage.setItem('poupoules-state', JSON.stringify({ eggsByDay, eggEntries, hens, activities, economics, transactions, profileName })); localStorage.removeItem('poupoules-wiped'); } catch (error) { console.warn('Poupoules: stockage local plein, données conservées en mémoire', error); } };
const toast = message => { const element = $('#toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2800); };
const euro = value => `${Number(value).toFixed(2).replace('.', ',')} €`;
const today = () => new Date().toISOString().slice(0, 10);
const weatherDescriptions = { 0: ['☀︎', 'Ciel dégagé'], 1: ['🌤️', 'Plutôt dégagé'], 2: ['⛅', 'Partiellement nuageux'], 3: ['☁︎', 'Couvert'], 45: ['🌫️', 'Brouillard'], 48: ['🌫️', 'Brouillard givrant'], 51: ['🌦️', 'Bruine légère'], 53: ['🌦️', 'Bruine'], 55: ['🌧️', 'Bruine forte'], 61: ['🌦️', 'Pluie légère'], 63: ['🌧️', 'Pluie'], 65: ['🌧️', 'Forte pluie'], 71: ['🌨️', 'Neige légère'], 73: ['🌨️', 'Neige'], 75: ['❄️', 'Forte neige'], 80: ['🌦️', 'Averses'], 81: ['🌧️', 'Averses soutenues'], 82: ['⛈️', 'Fortes averses'], 95: ['⛈️', 'Orage'], 96: ['⛈️', 'Orage et grêle'], 99: ['⛈️', 'Orage et forte grêle'] };
function renderWeather(current, stale = false) { const description = weatherDescriptions[current.weather_code] || ['☼', 'Conditions actuelles']; $('#weather-icon').textContent = description[0]; $('#weather-temp').innerHTML = `${Math.round(Number(current.temperature_2m))}°<sup>C</sup>`; $('#weather-condition').textContent = `${description[1]}${stale ? ' · dernière mesure' : ''}`; $('#weather-humidity').textContent = `${Math.round(Number(current.relative_humidity_2m))}%`; $('#weather-wind').textContent = `${Math.round(Number(current.wind_speed_10m))} km/h`; const uv = Number(current.uv_index); $('#weather-uv').textContent = uv < 3 ? 'Faible' : uv < 6 ? 'Modéré' : uv < 8 ? 'Élevé' : 'Très élevé'; }
function weatherFallback(message = 'Autorisez la localisation') { $('#weather-temp').innerHTML = `—<sup>°C</sup>`; $('#weather-condition').textContent = message; $('#weather-humidity').textContent = '—'; $('#weather-wind').textContent = '—'; $('#weather-uv').textContent = '—'; }
async function loadWeather() { const cached = (() => { try { return JSON.parse(localStorage.getItem('poupoules-weather') || 'null'); } catch { return null; } })(); if (cached?.current) renderWeather(cached.current, true); if (!navigator.geolocation) return weatherFallback('Géolocalisation indisponible'); navigator.geolocation.getCurrentPosition(async position => { try { const { latitude, longitude } = position.coords; const response = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude.toFixed(4)}&longitude=${longitude.toFixed(4)}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m,uv_index&timezone=auto`); if (!response.ok) throw new Error('weather'); const data = await response.json(); renderWeather(data.current); localStorage.setItem('poupoules-weather', JSON.stringify({ current: data.current, savedAt: Date.now() })); } catch { if (!cached?.current) weatherFallback('Météo indisponible'); } }, () => { if (!cached?.current) weatherFallback('Autorisez la localisation'); }, { enableHighAccuracy: false, maximumAge: 1800000, timeout: 8000 }); }

function closeDialog(dialog) { if (dialog?.open) dialog.close(); }
const breedEggColors = { Araucana: 'bleu', Ameraucana: 'bleu', 'Cream Legbar': 'bleu', 'Olive Egger': 'vert', Marans: 'chocolat', Rousse: 'brun', Harco: 'brun', Sussex: 'crème', Leghorn: 'blanc', Soie: 'blanc', Brahma: 'brun', Orpington: 'brun', Wyandotte: 'brun', Coucou: 'brun' };
const getHenEggColor = hen => hen?.eggColor || breedEggColors[hen?.breed] || 'brun';
function populateHenSelect(selected = '') { const target = $('#egg-hen'); if (!target) return; target.innerHTML = '<option value="">Non identifiée</option>' + hens.filter(h => h.status !== 'deceased').map(h => `<option value="${h.id}">${h.name} · ${getHenEggColor(h)}</option>`).join(''); target.value = selected; }
function getEntryLines(entry) { return entry?.lines?.length ? entry.lines : [{ count: entry?.count || 0, color: entry?.color || 'brun', henId: entry?.henId || '' }]; }
function renderEggLines(lines = [{ count: 1, color: 'brun', henId: '' }]) { $('#egg-lines').innerHTML = lines.map((line, index) => `<div class="egg-line" data-line-index="${index}"><label>Quantité<div class="quantity-stepper"><button class="quantity-minus" type="button" aria-label="Retirer un œuf">−</button><input class="line-count" type="text" inputmode="none" value="${line.count || 1}" readonly aria-label="Quantité d’œufs"><button class="quantity-plus" type="button" aria-label="Ajouter un œuf">＋</button></div></label><label>Couleur<select class="line-color"><option value="blanc">Blanc</option><option value="crème">Crème</option><option value="brun">Brun</option><option value="bleu">Bleu</option><option value="vert">Vert / bleu-vert</option><option value="chocolat">Chocolat</option><option value="tacheté">Tacheté</option></select></label><label>Poule<select class="line-hen"></select></label>${lines.length > 1 ? '<button class="remove-line" type="button" aria-label="Supprimer cette ligne">×</button>' : ''}</div>`).join(''); document.querySelectorAll('.egg-line').forEach((row, index) => { const line = lines[index]; row.querySelector('.line-color').value = line.color || 'brun'; const select = row.querySelector('.line-hen'); select.innerHTML = '<option value="">Non identifiée</option>' + hens.filter(h => h.status !== 'deceased').map(h => `<option value="${h.id}">${h.name} · ${getHenEggColor(h)}</option>`).join(''); select.value = line.henId || ''; const color = row.querySelector('.line-color'); const applyHenColor = () => { const hen = hens.find(item => item.id === select.value); if (hen) { color.value = getHenEggColor(hen); color.disabled = true; } else color.disabled = false; }; select.addEventListener('change', applyHenColor); applyHenColor(); const quantity = row.querySelector('.line-count'); row.querySelector('.quantity-minus').addEventListener('click', () => { quantity.value = Math.max(1, Number(quantity.value) - 1); updateEggTotal(); }); row.querySelector('.quantity-plus').addEventListener('click', () => { quantity.value = Math.min(99, Number(quantity.value) + 1); updateEggTotal(); }); row.querySelector('.remove-line')?.addEventListener('click', () => { row.remove(); updateEggTotal(); }); }); updateEggTotal(); }
function updateEggTotal() { const total = [...document.querySelectorAll('.line-count')].reduce((sum, input) => sum + (Number(input.value) || 0), 0); $('#egg-total').textContent = `${total} œuf${total > 1 ? 's' : ''}`; }
function formatEntryText(entry) { return getEntryLines(entry).map(line => { const hen = hens.find(item => item.id === line.henId); return `${line.count} × ${line.color}${hen ? ` · ${hen.name}` : ''}`; }).join(' + ') + (entry.note ? ` · ${entry.note}` : ''); }
function openEggDialog(entryId = null) { const entry = entryId ? eggEntries.find(item => item.id === entryId) : null; $('#egg-entry-id').value = entry?.id || ''; $('#egg-eyebrow').textContent = entry ? 'MODIFIER LA RÉCOLTE' : 'NOUVELLE ENTRÉE'; $('#egg-title').textContent = entry ? 'Modifier une récolte' : 'Ajouter une récolte'; $('#save-eggs').textContent = entry ? 'Enregistrer les modifications' : 'Enregistrer la récolte'; $('#egg-date').value = entry?.date || today(); $('#egg-note').value = entry?.note || ''; renderEggLines(getEntryLines(entry)); $('#egg-dialog').showModal(); }
function showPage(id) { document.querySelectorAll('.page').forEach(page => page.classList.toggle('active', page.id === id)); document.querySelectorAll('.tab').forEach(tab => tab.classList.toggle('active', tab.dataset.page === id)); window.scrollTo({ top: 0, behavior: 'smooth' }); }

function renderHens() {
  const active = hens.filter(h => h.status !== 'deceased');
  $('#hens-grid').innerHTML = active.length ? active.map(hen => `<button class="hen-card ${hen.status === 'rest' ? 'rest' : ''}" type="button" data-hen-id="${hen.id}"><div class="hen-avatar">${hen.photo ? `<img src="${hen.photo}" alt="Photo de ${hen.name}">` : hen.emoji || '🐔'}</div><div class="hen-info"><strong>${hen.name}</strong><span>${hen.breed || 'Race non renseignée'} · ${hen.status === 'rest' ? 'au repos' : 'active'}</span></div></button>`).join('') : '<div class="empty-state"><b>🐔</b>Aucune poule active pour le moment.<br>Ajoutez votre première poule.</div>';
  $('#active-hens').textContent = active.filter(h => h.status !== 'rest').length; $('#total-hens').textContent = active.length; $('#flock-count').textContent = active.length; $('#cemetery-count').textContent = hens.filter(h => h.status === 'deceased').length;
  $('#flock-sub').textContent = active.length ? 'Une équipe en pleine forme' : 'Ajoutez votre première poule';
  document.querySelectorAll('[data-hen-id]').forEach(card => card.addEventListener('click', () => openHenDialog(card.dataset.henId)));
}
function renderCemetery() {
  const dead = hens.filter(h => h.status === 'deceased');
  $('#cemetery-grid').innerHTML = dead.length ? dead.map(hen => `<button class="grave" type="button" data-hen-id="${hen.id}"><div class="grave-photo">${hen.photo ? `<img src="${hen.photo}" alt="Photo de ${hen.name}">` : hen.emoji || '🪦'}</div><div><strong>${hen.name}</strong><small>${hen.breed || 'Race non renseignée'} · ${hen.deathDate || 'Date inconnue'}</small>${hen.deathNote ? `<p>“${hen.deathNote}”</p>` : ''}</div></button>`).join('') : '<div class="empty-state"><b>🪦</b>Le cimetière est encore vide.</div>';
  document.querySelectorAll('.grave[data-hen-id]').forEach(card => card.addEventListener('click', () => openHenDialog(card.dataset.henId)));
}
function renderActivities() { $('#activity-list').innerHTML = activities.map(a => `<div class="activity-item"><div class="activity-icon">${a.icon}</div><div><strong>${a.title}</strong><span>${a.text}</span></div><span class="activity-time">${a.time}</span>${a.entryId ? `<button class="activity-edit" type="button" data-edit-entry="${a.entryId}">Modifier</button>` : ''}</div>`).join(''); $('#journal-total').textContent = eggsByDay.reduce((a, b) => a + b, 0); $('#journal-last').textContent = activities[0]?.time || 'Aucune'; document.querySelectorAll('[data-edit-entry]').forEach(button => button.addEventListener('click', () => openEggDialog(button.dataset.editEntry))); }
function renderChart() { const values = (eggsByDay.length ? eggsByDay : [0]).slice(-Number($('#period-select').value)); const step = 600 / Math.max(values.length - 1, 1); const points = values.map((value, index) => [index * step, 170 - (value / 10) * 145]); const line = points.map((point, index) => `${index ? 'L' : 'M'}${point[0].toFixed(1)} ${point[1].toFixed(1)}`).join(' '); $('#chart-line').setAttribute('d', line); $('#chart-area').setAttribute('d', `${line} L${points.at(-1)[0]} 175 L0 175 Z`); $('#chart-dots').innerHTML = points.map(([x, y]) => `<circle class="chart-dot" cx="${x}" cy="${y}" r="5"/>`).join(''); $('#chart-days').innerHTML = values.map((_, index) => `<span>${['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'][(index + 1) % 7]}</span>`).join(''); $('#avg-eggs').innerHTML = `${(values.reduce((a, b) => a + b, 0) / values.length).toFixed(1).replace('.', ',')} <small>œufs</small>`; $('#today-eggs').textContent = eggsByDay.at(-1); }
function monthlyData() { const now = new Date(); const months = []; for (let i = 11; i >= 0; i--) { const date = new Date(now.getFullYear(), now.getMonth() - i, 1); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; const entries = eggEntries.filter(entry => String(entry.date || '').startsWith(key)); const eggs = entries.reduce((sum, entry) => sum + Number(entry.count || getEntryLines(entry).reduce((a, line) => a + Number(line.count || 0), 0)), 0); months.push({ key, label: date.toLocaleDateString('fr-FR', { month: 'short' }).replace('.', ''), eggs }); } return months; }
function monthTransactions(key) { return transactions.filter(item => String(item.date || '').startsWith(key)); }
function renderTransactions() { const target = $('#transaction-list'); if (!target) return; const recent = [...transactions].sort((a, b) => String(b.date).localeCompare(String(a.date))).slice(0, 8); $('#transaction-list').innerHTML = recent.length ? recent.map(item => `<div class="transaction-row"><span class="transaction-kind ${item.type}">${item.type === 'sale' ? '↗' : '↘'}</span><div><strong>${item.type === 'sale' ? 'Vente' : 'Achat'} · ${item.categoryLabel}</strong><small>${item.date}${item.note ? ` · ${item.note}` : ''}</small></div><b class="${item.type === 'sale' ? 'profit-positive' : 'profit-negative'}">${item.type === 'sale' ? '+' : '-'}${euro(item.amount)}</b><button type="button" class="transaction-delete" data-transaction-id="${item.id}" aria-label="Supprimer cette opération">×</button></div>`).join('') : '<p class="empty-transactions">Aucune opération enregistrée.</p>'; document.querySelectorAll('[data-transaction-id]').forEach(button => button.addEventListener('click', () => { transactions = transactions.filter(item => item.id !== button.dataset.transactionId); persist(); renderTransactions(); calculateStats(); })); }
function renderMonthlyStats() { const months = monthlyData(); const max = Math.max(...months.map(item => item.eggs), 1); const step = 720 / Math.max(months.length - 1, 1); const points = months.map((item, index) => [index * step, 195 - (item.eggs / max) * 165]); const line = points.map((point, index) => `${index ? 'L' : 'M'}${point[0].toFixed(1)} ${point[1].toFixed(1)}`).join(' '); $('#monthly-chart-line').setAttribute('d', line); $('#monthly-chart-area').setAttribute('d', `${line} L${points.at(-1)[0]} 200 L0 200 Z`); $('#monthly-chart-dots').innerHTML = points.map(([x, y], index) => `<circle class="chart-dot" cx="${x}" cy="${y}" r="5"><title>${months[index].label}: ${months[index].eggs} œufs</title></circle>`).join(''); $('#monthly-labels').innerHTML = months.map(item => `<span>${item.label}</span>`).join(''); $('#monthly-max').textContent = max; const current = months.at(-1); const currentOps = monthTransactions(current.key); const sales = currentOps.filter(item => item.type === 'sale').reduce((sum, item) => sum + Number(item.amount || 0), 0); const purchases = currentOps.filter(item => item.type === 'purchase').reduce((sum, item) => sum + Number(item.amount || 0), 0); const estimatedRevenue = current.eggs / 6 * Number(economics.boxPrice || 0); const revenue = sales || estimatedRevenue; const profit = revenue - purchases; $('#stat-month-eggs').textContent = current.eggs; $('#stat-month-label').textContent = current.label; $('#stat-revenue').textContent = euro(revenue); $('#stat-cost').textContent = euro(purchases); $('#stat-profit').textContent = euro(profit); $('#stat-profit').className = profit >= 0 ? 'profit-positive' : 'profit-negative'; $('#profit-detail').textContent = `${euro(purchases)} d’achats · ${sales ? 'ventes saisies' : 'vente estimée'}`; $('#monthly-summary').innerHTML = months.slice(-6).reverse().map(item => { const ops = monthTransactions(item.key); const salesTotal = ops.filter(op => op.type === 'sale').reduce((sum, op) => sum + Number(op.amount || 0), 0); const costs = ops.filter(op => op.type === 'purchase').reduce((sum, op) => sum + Number(op.amount || 0), 0); const rec = salesTotal || item.eggs / 6 * Number(economics.boxPrice || 0); const net = rec - costs; return `<div class="month-row"><div><strong>${item.label}</strong><small>${item.eggs} œufs · ${ops.length} opération${ops.length > 1 ? 's' : ''}</small></div><b class="${net >= 0 ? 'profit-positive' : 'profit-negative'}">${euro(net)}</b></div>`; }).join(''); }
function calculateStats() { renderMonthlyStats(); renderTransactions(); $('#breed-stats').innerHTML = hens.filter(h => h.status !== 'deceased').map(h => { const count = eggEntries.reduce((sum, entry) => sum + getEntryLines(entry).filter(line => line.henId === h.id).reduce((lineSum, line) => lineSum + Number(line.count || 0), 0), 0); const rate = Math.min(100, count / 30 * 100); return `<div class="breed-row"><div class="breed-name"><span>${h.emoji || '🐔'}</span><strong>${h.breed || 'Autre'}</strong><small>${h.name} · ${count} œuf${count > 1 ? 's' : ''} · ${getHenEggColor(h)}</small></div><div class="progress-track"><i style="width:${rate}%"></i></div><b>${rate.toFixed(0)}%</b></div>`; }).join(''); }
function renderProfile() { const name = profileName || currentUser?.displayName || currentUser?.email?.split('@')[0] || 'Éleveur'; $('#profile-name').textContent = name; $('#profile-email').textContent = currentUser?.demo ? 'Mode démo local' : (currentUser?.email || 'Mode démo local'); $('#profile-big-avatar').textContent = name.charAt(0).toUpperCase(); $('#top-avatar').textContent = name.charAt(0).toUpperCase(); $('#auth-state').textContent = currentUser?.demo ? 'Mode démo local' : (currentUser ? 'Connecté à Firebase' : 'Mode démo local'); $('#signout-button').hidden = !currentUser; $('#open-auth').hidden = !!currentUser && !currentUser.demo; $('#hero-name').textContent = `${name}.`; }
function renderVersion() { $('#app-version').textContent = `v${APP_VERSION}`; }

function openHenDialog(id = null) { editingHenId = id; pendingPhoto = ''; const hen = hens.find(item => item.id === id); $('#hen-form').reset(); $('#hen-breed').value = 'Autre'; $('#hen-egg-color').value = 'brun'; $('#hen-error').textContent = ''; $('#hen-title').textContent = hen ? `Modifier ${hen.name}` : 'Ajouter une poule'; $('#hen-eyebrow').textContent = hen ? 'FICHE DE LA POULE' : 'NOUVELLE POULE'; $('#hen-extra').hidden = !hen; $('#hen-deceased').hidden = !hen || hen.status === 'deceased'; $('#hen-restore').hidden = !hen || hen.status !== 'deceased'; $('#hen-delete').hidden = !hen; $('#hen-photo-remove').hidden = true; $('#hen-photo-preview').innerHTML = '📷'; if (hen) { $('#hen-name').value = hen.name; $('#hen-breed').value = hen.breed || ''; $('#hen-egg-color').value = hen.eggColor || 'brun'; $('#hen-arrival').value = hen.arrivalDate || ''; $('#hen-status').value = hen.status === 'rest' ? 'rest' : 'active'; pendingPhoto = hen.photo || ''; if (hen.photo) { $('#hen-photo-preview').innerHTML = `<img src="${hen.photo}" alt="Photo actuelle">`; $('#hen-photo-remove').hidden = false; } } $('#hen-dialog').showModal(); }
function readPhoto(file) { if (!file) return; if (file.size > 8 * 1024 * 1024) { $('#hen-error').textContent = 'La photo doit faire moins de 8 Mo.'; return; } const url = URL.createObjectURL(file); const image = new Image(); image.onload = () => { const max = 720; const ratio = Math.min(1, max / Math.max(image.naturalWidth, image.naturalHeight)); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.naturalWidth * ratio)); canvas.height = Math.max(1, Math.round(image.naturalHeight * ratio)); const context = canvas.getContext('2d'); context.fillStyle = '#f5f3eb'; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(image, 0, 0, canvas.width, canvas.height); pendingPhoto = canvas.toDataURL('image/jpeg', .78); $('#hen-photo-preview').innerHTML = `<img src="${pendingPhoto}" alt="Nouvelle photo">`; $('#hen-photo-remove').hidden = false; URL.revokeObjectURL(url); }; image.onerror = () => { URL.revokeObjectURL(url); $('#hen-error').textContent = 'Cette photo ne peut pas être utilisée.'; }; image.src = url; }
function saveHen(event) { event.preventDefault(); const name = $('#hen-name').value.trim(); if (!name) { $('#hen-error').textContent = 'Donnez un nom à cette poule.'; return; } const existing = editingHenId && hens.find(item => item.id === editingHenId); const hen = existing || { id: `hen-${Date.now()}`, emoji: '🐔' }; Object.assign(hen, { name, breed: $('#hen-breed').value || 'Race non renseignée', eggColor: $('#hen-egg-color').value || 'brun', arrivalDate: $('#hen-arrival').value || '', status: $('#hen-status').value, photo: pendingPhoto || '' }); if (!existing) hens.push(hen); persist(); renderHens(); renderCemetery(); calculateStats(); closeDialog($('#hen-dialog')); toast(existing ? `${name} a été modifiée` : `${name} a été ajoutée au poulailler`); }
function declareDeceased() { if (!editingHenId) return; $('#death-date').value = today(); $('#death-note').value = ''; $('#death-title').textContent = `Déclarer ${hens.find(h => h.id === editingHenId)?.name || 'la poule'} décédée`; closeDialog($('#hen-dialog')); $('#death-dialog').showModal(); }
function confirmDeath(event) { event.preventDefault(); const hen = hens.find(item => item.id === editingHenId); if (!hen) return; hen.status = 'deceased'; hen.deathDate = $('#death-date').value || today(); hen.deathNote = $('#death-note').value.trim(); persist(); renderHens(); renderCemetery(); calculateStats(); closeDialog($('#death-dialog')); toast(`${hen.name} a rejoint le cimetière`); }
function restoreHen() { const hen = hens.find(item => item.id === editingHenId); if (!hen) return; hen.status = 'active'; delete hen.deathDate; delete hen.deathNote; persist(); renderHens(); renderCemetery(); calculateStats(); closeDialog($('#hen-dialog')); toast(`${hen.name} est de retour dans le poulailler`); }
function deleteHen() { const hen = hens.find(item => item.id === editingHenId); if (!hen || !window.confirm(`Supprimer définitivement la fiche de ${hen.name} ?`)) return; hens = hens.filter(item => item.id !== editingHenId); persist(); renderHens(); renderCemetery(); calculateStats(); closeDialog($('#hen-dialog')); toast('Fiche supprimée'); }

async function initFirebase() { try { const app = initializeApp(firebaseConfig); firestore = getFirestore(app); auth = getAuth(app); onAuthStateChanged(auth, user => { if (!user && currentUser?.demo) { renderProfile(); return; } currentUser = user; renderProfile(); if (unsubscribeEggs) unsubscribeEggs(); if (!user) return; const entries = query(collection(firestore, 'egg_entries'), where('userId', '==', user.uid), orderBy('createdAt', 'desc'), limit(30)); unsubscribeEggs = onSnapshot(entries, snapshot => { if (!snapshot.empty) { eggEntries = snapshot.docs.map(item => ({ id: item.id, firestoreId: item.id, ...item.data() })); activities = eggEntries.map(entry => ({ entryId: entry.id, icon: '🥚', title: 'Récolte enregistrée', text: formatEntryText(entry), time: entry.date || 'Date inconnue' })); eggsByDay = eggEntries.map(item => Number(item.count || 0)).slice(-14); persist(); } renderChart(); renderActivities(); calculateStats(); }, () => { renderChart(); renderActivities(); calculateStats(); }); }); await getRedirectResult(auth).catch(() => {}); } catch (error) { console.info('Firebase indisponible', error); renderProfile(); } }
async function saveEggEntry(event) { event.preventDefault(); const rows = [...document.querySelectorAll('.egg-line')]; const lines = rows.map(row => ({ count: Math.max(1, Number(row.querySelector('.line-count').value) || 0), color: row.querySelector('.line-color').value, henId: row.querySelector('.line-hen').value })); if (!lines.length) return toast('Ajoutez au moins une ligne de récolte'); const count = lines.reduce((sum, line) => sum + line.count, 0); const id = $('#egg-entry-id').value || `egg-${Date.now()}`; const data = { id, date: $('#egg-date').value || today(), count, lines, note: $('#egg-note').value.trim(), createdAt: Date.now() }; const existing = eggEntries.find(entry => entry.id === id); if (existing) Object.assign(existing, data); else { eggEntries.unshift(data); eggsByDay = [...eggsByDay, count].slice(-14); } const activity = activities.find(item => item.entryId === id); const text = formatEntryText(data); if (activity) { activity.text = text; activity.time = data.date; activity.title = 'Récolte modifiée'; } else activities.unshift({ entryId: id, icon: '🥚', title: 'Récolte enregistrée', text, time: data.date }); persist(); renderChart(); renderActivities(); calculateStats(); if (firestore && currentUser && !currentUser.demo) { try { const payload = { count, lines, note: data.note, date: data.date, userId: currentUser.uid, createdAt: data.createdAt }; if (existing?.firestoreId) await updateDoc(doc(firestore, 'egg_entries', existing.firestoreId), payload); else { const ref = await addDoc(collection(firestore, 'egg_entries'), payload); data.firestoreId = ref.id; data.id = ref.id; const savedActivity = activities.find(item => item.entryId === id); if (savedActivity) savedActivity.entryId = ref.id; persist(); } } catch { toast('Récolte gardée en local : vérifiez les règles Firestore'); } } closeDialog($('#egg-dialog')); toast(existing ? 'Récolte modifiée' : `${count} œufs enregistrés en une seule fois`); }
async function handleGoogleAuth() { if (!auth) return $('#auth-error').textContent = 'Firebase est inaccessible.'; try { const provider = new GoogleAuthProvider(); provider.setCustomParameters({ prompt: 'select_account' }); await signInWithPopup(auth, provider); closeDialog($('#auth-dialog')); toast('Connexion Google réussie'); } catch (error) { if (error.code === 'auth/popup-blocked' || error.code === 'auth/popup-closed-by-user') return signInWithRedirect(auth, new GoogleAuthProvider()); const map = { 'auth/operation-not-allowed': 'Activez Google dans Firebase Console → Authentication → Sign-in method.', 'auth/unauthorized-domain': 'Ajoutez ce domaine dans Firebase → Authentication → Settings → Authorized domains.', 'auth/network-request-failed': 'Connexion réseau impossible, réessayez.' }; $('#auth-error').textContent = map[error.code] || `Google : ${error.code || 'erreur inconnue'}`; } }
function setAuthMode(mode) { $('#auth-submit').dataset.mode = mode; $('#auth-submit').textContent = mode === 'signup' ? 'Créer mon compte' : 'Se connecter'; $('#auth-title').textContent = mode === 'signup' ? 'Créer votre compte' : 'Ravi de vous revoir'; $('#auth-name-field').hidden = mode !== 'signup'; $('#auth-toggle').textContent = mode === 'signup' ? 'J’ai déjà un compte' : 'Créer un compte'; }
async function handleAuth(event) { event.preventDefault(); const email = $('#auth-email').value.trim(); const password = $('#auth-password').value; const name = $('#auth-name').value.trim(); const mode = $('#auth-submit').dataset.mode; $('#auth-error').textContent = ''; if (!email || password.length < 6) return $('#auth-error').textContent = 'E-mail valide et mot de passe de 6 caractères minimum requis.'; try { let credential; if (mode === 'signup') { credential = await createUserWithEmailAndPassword(auth, email, password); if (name) await updateProfile(credential.user, { displayName: name }); } else credential = await signInWithEmailAndPassword(auth, email, password); closeDialog($('#auth-dialog')); $('#auth-form').reset(); toast('Connexion Firebase réussie'); } catch (error) { const map = { 'auth/operation-not-allowed': 'Activez Email/Password dans Firebase Console.', 'auth/invalid-credential': 'E-mail ou mot de passe incorrect.', 'auth/email-already-in-use': 'Cet e-mail possède déjà un compte.', 'auth/weak-password': 'Le mot de passe doit contenir au moins 6 caractères.', 'auth/invalid-email': 'Cet e-mail n’est pas valide.' }; $('#auth-error').textContent = map[error.code] || `Firebase : ${error.code || 'erreur inconnue'}`; } }
async function wipeAllData() { const confirmed = $('#wipe-confirm').value.trim().toUpperCase() === 'SUPPRIMER'; if (!confirmed) return $('#wipe-error').textContent = 'Tapez exactement SUPPRIMER pour confirmer.'; $('#wipe-submit').disabled = true; let cloudError = false; try { if (firestore && currentUser && !currentUser.demo) { try { const entries = await getDocs(query(collection(firestore, 'egg_entries'), where('userId', '==', currentUser.uid))); await Promise.all(entries.docs.map(entry => deleteDoc(entry.ref))); } catch { cloudError = true; } } } finally { localStorage.removeItem('poupoules-state'); localStorage.setItem('poupoules-wiped', '1'); localStorage.removeItem('poupoules-demo'); eggsByDay = []; eggEntries = []; hens = []; activities = []; economics = { boxPrice: 0 }; transactions = []; profileName = ''; renderHens(); renderCemetery(); renderActivities(); renderChart(); calculateStats(); renderProfile(); closeDialog($('#wipe-dialog')); $('#wipe-submit').disabled = false; toast(cloudError ? 'Données locales supprimées. La suppression Firestore a échoué, réessayez connecté.' : 'Toutes vos données ont été supprimées'); } }
async function forceUpdate() { const registration = await navigator.serviceWorker?.getRegistration(); if (!registration) return toast('Mise à jour disponible au prochain lancement'); registration.addEventListener('updatefound', () => toast('Mise à jour téléchargée')); await registration.update(); registration.active?.postMessage({ type: 'SKIP_WAITING' }); toast('Mise à jour vérifiée — rechargez si nécessaire'); }
function exportData() { const blob = new Blob([JSON.stringify({ version: APP_VERSION, hens, eggsByDay, activities, economics, transactions, user: currentUser?.email || null }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'poupoules-export.json'; link.click(); URL.revokeObjectURL(url); toast('Export téléchargé'); }

// Navigation et boutons globaux.
document.querySelectorAll('.tab, .quick-action, [data-page]').forEach(button => button.addEventListener('click', () => showPage(button.dataset.page)));
document.querySelectorAll('[data-close]').forEach(button => button.addEventListener('click', () => closeDialog(button.closest('dialog'))));
$('#period-select').addEventListener('change', renderChart); $('#quick-harvest-float').addEventListener('click', openEggDialog);
$('#settings-button').addEventListener('click', () => { renderVersion(); $('#settings-dialog').showModal(); }); $('#profile-button').addEventListener('click', () => { renderProfile(); $('#profile-dialog').showModal(); }); $('#hero-name-button').addEventListener('click', () => { $('#name-input').value = profileName || currentUser?.displayName || ''; $('#name-dialog').showModal(); });
$('#add-hen').addEventListener('click', () => openHenDialog()); $('#open-cemetery').addEventListener('click', () => showPage('page-cemetery')); $('#hen-save').addEventListener('click', saveHen); $('#hen-photo-input').addEventListener('change', event => readPhoto(event.target.files[0])); $('#hen-photo-pick').addEventListener('click', () => $('#hen-photo-input').click()); $('#hen-photo-remove').addEventListener('click', () => { pendingPhoto = ''; $('#hen-photo-preview').innerHTML = '📷'; $('#hen-photo-remove').hidden = true; }); $('#hen-deceased').addEventListener('click', declareDeceased); $('#hen-restore').addEventListener('click', restoreHen); $('#hen-delete').addEventListener('click', deleteHen); $('#death-form').addEventListener('submit', confirmDeath);
$('#egg-form').addEventListener('submit', saveEggEntry); $('#add-egg-line').addEventListener('click', () => { const lines = [...document.querySelectorAll('.egg-line')].map(row => ({ count: Number(row.querySelector('.line-count').value) || 1, color: row.querySelector('.line-color').value, henId: row.querySelector('.line-hen').value })); lines.push({ count: 1, color: 'brun', henId: '' }); renderEggLines(lines); });
$('#name-form').addEventListener('submit', async event => { event.preventDefault(); const value = $('#name-input').value.trim(); if (!value) return; profileName = value; persist(); if (currentUser && !currentUser.demo) await updateProfile(currentUser, { displayName: value }); renderProfile(); closeDialog($('#name-dialog')); toast('Votre prénom a été mis à jour'); });
$('#economics-form')?.addEventListener('submit', event => { event.preventDefault(); economics = { boxPrice: Number($('#box-price').value) || 0 }; persist(); calculateStats(); toast('Prix de vente enregistré'); }); $('#transaction-form')?.addEventListener('submit', event => { event.preventDefault(); const category = $('#transaction-category'); transactions.unshift({ id: `transaction-${Date.now()}`, date: $('#transaction-date').value || today(), type: $('#transaction-type').value, category: category.value, categoryLabel: category.options[category.selectedIndex].textContent, amount: Number($('#transaction-amount').value) || 0, note: $('#transaction-note').value.trim() }); persist(); event.target.reset(); $('#transaction-date').value = today(); renderTransactions(); calculateStats(); toast('Opération ajoutée au journal'); });
$('#export-data').addEventListener('click', exportData); $('#force-update').addEventListener('click', forceUpdate); $('#open-wipe').addEventListener('click', () => { $('#wipe-confirm').value = ''; $('#wipe-error').textContent = ''; $('#wipe-submit').disabled = true; $('#wipe-cloud-note').hidden = !currentUser || currentUser.demo; closeDialog($('#settings-dialog')); $('#wipe-dialog').showModal(); }); $('#wipe-confirm').addEventListener('input', event => { $('#wipe-submit').disabled = event.target.value.trim().toUpperCase() !== 'SUPPRIMER'; }); $('#wipe-form').addEventListener('submit', event => { event.preventDefault(); wipeAllData(); });
$('#auth-form').addEventListener('submit', handleAuth); $('#auth-toggle').addEventListener('click', event => { event.preventDefault(); setAuthMode($('#auth-submit').dataset.mode === 'signup' ? 'login' : 'signup'); }); $('#open-auth').addEventListener('click', () => { closeDialog($('#profile-dialog')); setAuthMode('login'); $('#auth-dialog').showModal(); }); $('#google-auth').addEventListener('click', handleGoogleAuth); $('#demo-auth').addEventListener('click', () => { currentUser = { demo: true, displayName: 'Éleveur démo', email: 'Démo locale' }; localStorage.setItem('poupoules-demo', '1'); closeDialog($('#auth-dialog')); renderProfile(); toast('Mode démo activé — vos données restent sur cet appareil'); }); $('#signout-button').addEventListener('click', async () => { if (currentUser?.demo) { currentUser = null; localStorage.removeItem('poupoules-demo'); } else if (auth) await signOut(auth); closeDialog($('#profile-dialog')); renderProfile(); toast('Vous êtes déconnecté'); });

$('#hen-breed').addEventListener('change', event => { const defaults = breedEggColors; if (defaults[event.target.value]) $('#hen-egg-color').value = defaults[event.target.value]; }); populateHenSelect(); $('#box-price').value = economics.boxPrice; if ($('#transaction-date')) $('#transaction-date').value = today(); $('#app-version').textContent = `v${APP_VERSION}`;
if (localStorage.getItem('poupoules-demo')) currentUser = { demo: true, displayName: 'Éleveur démo', email: 'Démo locale' };
renderHens(); renderCemetery(); renderActivities(); renderChart(); calculateStats(); renderProfile(); loadWeather(); window.setInterval(loadWeather, 30 * 60 * 1000); initFirebase();
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
